import { ethers } from "ethers";
import * as Kuru from "@kuru-labs/kuru-sdk";
const provider = new ethers.providers.StaticJsonRpcProvider("https://rpc.monad.xyz", 143);
const MARKET = "0x065C9d28E428A0db40191a54d33d5b7c71a9C394";
const params = await Kuru.ParamFetcher.getMarketParams(provider, MARKET);
const book = await Kuru.OrderBook.getFormattedL2OrderBook(provider, MARKET, params);
console.log("asks n", book.asks.length, "first", book.asks[0], "last", book.asks.at(-1));
console.log("bids n", book.bids.length, "first", book.bids[0], "last", book.bids.at(-1));
console.log("vault", JSON.stringify(book.vaultParams, (k, v) => (v?._hex ? v.toString() : v)));
console.log("manual asks", book.manualOrders.asks.slice(-2), "manual bids", book.manualOrders.bids.slice(0, 2));
const gp = await provider.getGasPrice(); console.log("gasPrice gwei", ethers.utils.formatUnits(gp, "gwei"));
const raw = await fetch("https://rpc.monad.xyz", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_sendRawTransactionSync", params: ["0x00"] }) });
console.log("sendRawTransactionSync probe:", await raw.text());
